"use client";

import dynamic from "next/dynamic";
import { useEffect, useRef, useState } from "react";
import Button from "../../../ui_elements/button/Button";

const MapWithNoSSR = dynamic(
  () => import("../../../localisation/MapComponent"),
  {
    ssr: false,
    loading: () => <p>Loading map...</p>,
  }
);

function GlobalMap() {
  // Example data for hangars
  const data = [
    {
      name: null,
      province: null,
      commune: null,
      zone: null,
      latitude: 0,
      longitude: 0,
    },
    {
      name: "Salle Communal",
      province: "Bubanza",
      commune: "Bubanza",
      zone: "Bubanza",
      latitude: -3.08449,
      longitude: 29.39367,
    },
    {
      name: "Colline Muramba",
      province: "Bubanza",
      commune: "Bubanza",
      zone: "Muramba",
      latitude: -3.03623,
      longitude: 29.38706,
    },
    {
      name: "Coop.Muhini Girijambo",
      province: "Bubanza",
      commune: "Bubanza",
      zone: "Buvyuko",
      latitude: -3.03426,
      longitude: 29.31103,
    },
    {
      name: "Zone Buvyuko",
      province: "Bubanza",
      commune: "Bubanza",
      zone: "Buvyuko",
      latitude: -3.0592,
      longitude: 29.3487,
    },
    {
      name: "Hangar Caem",
      province: "Bubanza",
      commune: "Bubanza",
      zone: "Mitakataka",
      latitude: -3.14545,
      longitude: 29.36548,
    },
    {
      name: "Salle Communal",
      province: "Bubanza",
      commune: "Bubanza",
      zone: "Muramba",
      latitude: -3.01526,
      longitude: 29.34781,
    },
    {
      name: "Lycee Communal Kivyuka",
      province: "Bubanza",
      commune: "Musigati",
      zone: "Kivyuka",
      latitude: -3.02861,
      longitude: 29.4506,
    },
    {
      name: "Hangar De La Coopertive Ndangamuco",
      province: "Bubanza",
      commune: "Musigati",
      zone: "Musigati",
      latitude: -3.0665,
      longitude: 29.45906,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Bubanza",
      commune: "Musigati",
      zone: "Ntamba",
      latitude: -2.98406,
      longitude: 29.43649,
    },
    {
      name: "Hangar Kazoza Kimiryango",
      province: "Bubanza",
      commune: "Musigati",
      zone: "Muyebe",
      latitude: -3.1371,
      longitude: 29.50251,
    },
    {
      name: "Hangar Zonal)",
      province: "Bubanza",
      commune: "Rugazi",
      zone: "Ruce",
      latitude: -3.17027,
      longitude: 29.50207,
    },
    {
      name: "Hangar Communal Giharabuga",
      province: "Bubanza",
      commune: "Rugazi",
      zone: "Rugazi",
      latitude: -3.23811,
      longitude: 29.47481,
    },
    {
      name: "Hangar Caprimu Village 4",
      province: "Bubanza",
      commune: "Gihanga",
      zone: "Buringa",
      latitude: -3.23962,
      longitude: 29.31481,
    },
    {
      name: "Coopertive Abanyabikorwa V2",
      province: "Bubanza",
      commune: "Gihanga",
      zone: "Gihanga",
      latitude: -3.1779,
      longitude: 29.32669,
    },
    {
      name: "Hangar De La Cooperative Dukundibikorwa",
      province: "Bubanza",
      commune: "Mpanda",
      zone: "Butanuka",
      latitude: -3.16549,
      longitude: 29.40035,
    },
    {
      name: "Hangar De La Cooperative Twizigirane",
      province: "Bubanza",
      commune: "Mpanda",
      zone: "Musenyi",
      latitude: -3.20151,
      longitude: 29.40408,
    },
    {
      name: "Hangar Fao",
      province: "Bubanza",
      commune: "Rugazi",
      zone: "Muzinda",
      latitude: -3.25825,
      longitude: 29.41793,
    },
    {
      name: "Hangar Projet Maraicher",
      province: "Bujumbura Mairie",
      commune: "Ntahangwa",
      zone: "Ngagara",
      latitude: -3.34619,
      longitude: 29.37286,
    },
    {
      name: "Nyakabiga-Centre Jeune",
      province: "Bujumbura Mairie",
      commune: "Mukaza",
      zone: "Nyakabiga",
      latitude: -3.3719,
      longitude: 29.38306,
    },
    {
      name: "Hangar Commune Muha",
      province: "Bujumbura Mairie",
      commune: "Muha",
      zone: "Kanyosha",
      latitude: -3.43115,
      longitude: 29.35886,
    },
    {
      name: "Bureau De La Zone Kibuye",
      province: "Bujumbura Rural",
      commune: "Isare",
      zone: "Kibuye",
      latitude: -3.39068,
      longitude: 29.50811,
    },
    {
      name: "Bureau Zonal Nyambuye",
      province: "Bujumbura Rural",
      commune: "Isare",
      zone: "Nyambuye",
      latitude: -3.36578,
      longitude: 29.44195,
    },
    {
      name: "HANGAR KIGEZI EN FACE DU COMMISARIAT COMMUNAL",
      province: "Bujumbura Rural",
      commune: "Isare",
      zone: "Rushubi",
      latitude: -3.34283,
      longitude: 29.48183,
    },
    {
      name: "Bureau Zonal Benga",
      province: "Bujumbura Rural",
      commune: "Isare",
      zone: "Benga",
      latitude: -3.32184,
      longitude: 29.44395,
    },
    {
      name: "C.E.M Mageyo",
      province: "Bujumbura Rural",
      commune: "Mubimbi",
      zone: "Mageyo",
      latitude: -3.32943,
      longitude: 29.49033,
    },
    {
      name: "Salle Communal",
      province: "Bujumbura Rural",
      commune: "Mubimbi",
      zone: "Mubimbi",
      latitude: -3.28214,
      longitude: 29.49645,
    },
    {
      name: "Grenier Communautaire  Chef Lieu De La Commune",
      province: "Bujumbura Rural",
      commune: "Mukike",
      zone: "Mayuyu",
      latitude: -3.57687,
      longitude: 29.50837,
    },
    {
      name: "Bureau Zonal Rukina",
      province: "Bujumbura Rural",
      commune: "Mukike",
      zone: "Rukina",
      latitude: -3.52646,
      longitude: 29.51678,
    },
    {
      name: "Salle Du Lycée Communal Bikanka",
      province: "Bujumbura Rural",
      commune: "Mukike",
      zone: "Bikanka",
      latitude: -3.53247,
      longitude: 29.56481,
    },
    {
      name: "Grenier Communautaire  De Matara",
      province: "Bujumbura Rural",
      commune: "Nyabiraba",
      zone: "Matara",
      latitude: -3.48282,
      longitude: 29.47967,
    },
    {
      name: "Bureau Communal",
      province: "Bujumbura Rural",
      commune: "Nyabiraba",
      zone: "Nyabiraba",
      latitude: -3.45592,
      longitude: 29.46258,
    },
    {
      name: "Salle Du Cds Kigina",
      province: "Bujumbura Rural",
      commune: "Nyabiraba",
      zone: "Kigina",
      latitude: -3.49348,
      longitude: 29.44229,
    },
    {
      name: "Grénier Communautaire",
      province: "Bujumbura Rural",
      commune: "Nyabiraba",
      zone: "Nyabibondo",
      latitude: -3.44373,
      longitude: 29.48367,
    },
    {
      name: "Hangar C.E.M Migera",
      province: "Bujumbura Rural",
      commune: "Kabezi",
      zone: "Migera",
      latitude: -3.53882,
      longitude: 29.35189,
    },
    {
      name: "Hangar Pradigel",
      province: "Bujumbura Rural",
      commune: "Kabezi",
      zone: "Ramba",
      latitude: -3.52565,
      longitude: 29.34424,
    },
    {
      name: "Hangar Bureau Zonal Mubone",
      province: "Bujumbura Rural",
      commune: "Kabezi",
      zone: "Mubone",
      latitude: -3.50792,
      longitude: 29.38066,
    },
    {
      name: "Bureau De La Zone",
      province: "Bujumbura Rural",
      commune: "Mutimbuzi",
      zone: "Gatumba",
      latitude: -3.33254,
      longitude: 29.24894,
    },
    {
      name: "Colline Kirwati I",
      province: "Bujumbura Rural",
      commune: "Mutimbuzi",
      zone: "Rukaramu",
      latitude: -3.29189,
      longitude: 29.3097,
    },
    {
      name: "Bureau Zonal Maramvya",
      province: "Bujumbura Rural",
      commune: "Mutimbuzi",
      zone: "Maramvya",
      latitude: -3.29866,
      longitude: 29.34959,
    },
    {
      name: "Hangar Kivoga Kw'Ipero",
      province: "Bujumbura Rural",
      commune: "Mutimbuzi",
      zone: "Rubirizi",
      latitude: -3.28951,
      longitude: 29.4049,
    },
    {
      name: "Hangar Kivoga Kw'Ipero",
      province: "Bujumbura Rural",
      commune: "Mutimbuzi",
      zone: "Rubirizi",
      latitude: -3.28923,
      longitude: 29.40494,
    },
    {
      name: "Hangar Kivoga Kw'Ipero",
      province: "Bujumbura Rural",
      commune: "Mutimbuzi",
      zone: "Rubirizi",
      latitude: -3.2886,
      longitude: 29.40507,
    },
    {
      name: "Commisarial Communal",
      province: "Bururi",
      commune: "Bururi",
      zone: "Buburi",
      latitude: -3.9496,
      longitude: 29.62415,
    },
    {
      name: "Cem Muzenga",
      province: "Bururi",
      commune: "Bururi",
      zone: "Muzenga",
      latitude: -3.95392,
      longitude: 29.69064,
    },
    {
      name: "Bureau Zonal",
      province: "Bururi",
      commune: "Bururi",
      zone: "Munini",
      latitude: -4.00899,
      longitude: 29.73972,
    },
    {
      name: "A Kirungo Maison Personnel Louee",
      province: "Bururi",
      commune: "Vyanda",
      zone: "Gitsiro",
      latitude: -4.02074,
      longitude: 29.54084,
    },
    {
      name: "Bureau Zonal",
      province: "Bururi",
      commune: "Bururi",
      zone: "Bamba",
      latitude: -3.94116,
      longitude: 29.76808,
    },
    {
      name: "Bureau Zonal",
      province: "Bururi",
      commune: "Songa",
      zone: "Kiryama",
      latitude: -3.85836,
      longitude: 29.71974,
    },
    {
      name: "Boutique  Mais A Deplacer Vers Cem Ruvumvu",
      province: "Bururi",
      commune: "Songa",
      zone: "Ndago",
      latitude: -3.86912,
      longitude: 29.66596,
    },
    {
      name: "Cem Ruvumvu",
      province: "Bururi",
      commune: "Songa",
      zone: "Ruvumu",
      latitude: -3.83164,
      longitude: 29.66083,
    },
    {
      name: "Infrastructure De L'Ancien Chef-Lieu Communal A Rumeza",
      province: "Bururi",
      commune: "Songa",
      zone: "Songa",
      latitude: -3.83042,
      longitude: 29.62477,
    },
    {
      name: "Maison Du Marche Manyoni",
      province: "Bururi",
      commune: "Songa",
      zone: "Muheka",
      latitude: -3.84442,
      longitude: 29.62389,
    },
    {
      name: "Maison Du Marche De Tora",
      province: "Bururi",
      commune: "Mugamba",
      zone: "Kibezi",
      latitude: -3.68598,
      longitude: 29.56336,
    },
    {
      name: "Salle Communal",
      province: "Bururi",
      commune: "Mugamba",
      zone: "Muramba",
      latitude: -3.66498,
      longitude: 29.58648,
    },
    {
      name: "Salle Ecofo Mwumba",
      province: "Bururi",
      commune: "Mugamba",
      zone: "Mwumba",
      latitude: -3.74443,
      longitude: 29.60033,
    },
    {
      name: "Cercle Projet Kajondi Mais A Deplacer Vers Le Hangar De Stockage Du Projet",
      province: "Bururi",
      commune: "Rutovu",
      zone: "Kajondi",
      latitude: -3.8833,
      longitude: 29.77838,
    },
    {
      name: "Burea Zonal",
      province: "Bururi",
      commune: "Rutovu",
      zone: "Muhweza",
      latitude: -3.95059,
      longitude: 29.84191,
    },
    {
      name: "Maison Du Marche",
      province: "Bururi",
      commune: "Rutovu",
      zone: "Muzenga",
      latitude: -3.8666,
      longitude: 29.8465,
    },
    {
      name: "Burea Zonal",
      province: "Bururi",
      commune: "Matana",
      zone: "Gasibe",
      latitude: -3.69918,
      longitude: 29.73928,
    },
    {
      name: "Bureau Zonal Mais Deplace Vers",
      province: "Bururi",
      commune: "Matana",
      zone: "Gisarenda",
      latitude: -3.77705,
      longitude: 29.72305,
    },
    {
      name: "Maison Du Marche Matana",
      province: "Bururi",
      commune: "Matana",
      zone: "Matana",
      latitude: -3.76555,
      longitude: 29.69046,
    },
    {
      name: "Burea Zonal",
      province: "Bururi",
      commune: "Rutovu",
      zone: "Condi",
      latitude: -3.80369,
      longitude: 29.83654,
    },
    {
      name: "Salle De La Cem Vyuya",
      province: "Bururi",
      commune: "Mugamba",
      zone: "Vyuya",
      latitude: -3.70759,
      longitude: 29.66238,
    },
    {
      name: "Hangar Cooperativ",
      province: "Cankuzo",
      commune: "Kigamba",
      zone: "Kigamba",
      latitude: -3.0678,
      longitude: 30.54143,
    },
    {
      name: "Hangar rujungu",
      province: "Cankuzo",
      commune: "Kigamba",
      zone: "Gitanga",
      latitude: -2.93656,
      longitude: 30.56061,
    },
    {
      name: "Centre De Quarentaine",
      province: "Cankuzo",
      commune: "Mishiha",
      zone: "Munzenze",
      latitude: -3.00764,
      longitude: 30.78921,
    },
    {
      name: "Hangar Prodema",
      province: "Cankuzo",
      commune: "Mishiha",
      zone: "Mugera",
      latitude: -3.06079,
      longitude: 30.71831,
    },
    {
      name: "Hangar Communal Kiniha Et Hangar Prodema",
      province: "Cankuzo",
      commune: "Mishiha",
      zone: "Mugera",
      latitude: -3.06477,
      longitude: 30.66816,
    },
    {
      name: "Hangar gasenyi mburi",
      province: "Cankuzo",
      commune: "Gisagara",
      zone: "Camazi",
      latitude: -3.17766,
      longitude: 30.82505,
    },
    {
      name: "Hangar murore",
      province: "Cankuzo",
      commune: "Gisagara",
      zone: "Gisagara",
      latitude: -3.18714,
      longitude: 30.66791,
    },
    {
      name: "Hangar Prodema",
      province: "Cankuzo",
      commune: "Gisagara",
      zone: "Camazi",
      latitude: -3.17255,
      longitude: 30.76248,
    },
    {
      name: "CEM Minyare",
      province: "Cankuzo",
      commune: "Cankuzo",
      zone: "Minyare",
      latitude: -3.21884,
      longitude: 30.49452,
    },
    {
      name: "Salle Uprona",
      province: "Cankuzo",
      commune: "Cankuzo",
      zone: "Cankuzo",
      latitude: -3.22187,
      longitude: 30.5492,
    },
    {
      name: "Hangar Flm",
      province: "Cankuzo",
      commune: "Cendajuru",
      zone: "Nyamugari",
      latitude: -3.32773,
      longitude: 30.55437,
    },
    {
      name: "Cem kiruhura",
      province: "Cankuzo",
      commune: "Cendajuru",
      zone: "Cendajuru",
      latitude: -3.2867,
      longitude: 30.60402,
    },
    {
      name: "Hangar Projet",
      province: "Cankuzo",
      commune: "Cendajuru",
      zone: "Twinkwavu",
      latitude: -3.26055,
      longitude: 30.65325,
    },
    {
      name: "Hangar Nyagisovu Cendajuru",
      province: "Cankuzo",
      commune: "Cendajuru",
      zone: "Twinkwavu",
      latitude: -3.32613,
      longitude: 30.61556,
    },
    {
      name: "Hangar Ruhagarika)",
      province: "Cibitoke",
      commune: "Buganda",
      zone: "Gasenyi",
      latitude: -2.99775,
      longitude: 29.22349,
    },
    {
      name: "Hangar De La Zone Ndava)",
      province: "Cibitoke",
      commune: "Buganda",
      zone: "Ndava",
      latitude: -3.02369,
      longitude: 29.25404,
    },
    {
      name: "Hangar De La Coopérative Duzikivi)",
      province: "Cibitoke",
      commune: "Bukinanyana",
      zone: "Ndora",
      latitude: -2.91466,
      longitude: 29.36574,
    },
    {
      name: "Buhoro",
      province: "Cibitoke",
      commune: "Mabayi",
      zone: "Buhoro",
      latitude: -2.71788,
      longitude: 29.19054,
    },
    {
      name: "Hangar Bureau Zonal Gahabura)",
      province: "Cibitoke",
      commune: "Bukinanyana",
      zone: "Gahabura",
      latitude: -2.88855,
      longitude: 29.29637,
    },
    {
      name: "Salle Communal",
      province: "Cibitoke",
      commune: "Bukinanyana",
      zone: "Bumba",
      latitude: -2.88123,
      longitude: 29.3365,
    },
    {
      name: "Hangar Zonal",
      province: "Cibitoke",
      commune: "Mabayi",
      zone: "Butahana",
      latitude: -2.74103,
      longitude: 29.25199,
    },
    {
      name: "Hangar Du Bpeae",
      province: "Cibitoke",
      commune: "Mabayi",
      zone: "Mabayi",
      latitude: -2.71531,
      longitude: 29.24405,
    },
    {
      name: "Home Dpe Ruhororo)",
      province: "Cibitoke",
      commune: "Mabayi",
      zone: "Rohororo",
      latitude: -2.63894,
      longitude: 29.22149,
    },
    {
      name: "Hangar Nyeshenza)",
      province: "Cibitoke",
      commune: "Mugina",
      zone: "Rugajo",
      latitude: -2.75089,
      longitude: 29.10866,
    },
    {
      name: "Hangar De La Bpae)",
      province: "Cibitoke",
      commune: "Rugombo",
      zone: "Cibitoke",
      latitude: -2.8845,
      longitude: 29.12224,
    },
    {
      name: "Salle De La Commune)",
      province: "Cibitoke",
      commune: "Rugombo",
      zone: "Rugombo",
      latitude: -2.80911,
      longitude: 29.08043,
    },
    {
      name: "Hangar De La Bpae)",
      province: "Cibitoke",
      commune: "Murwi",
      zone: "Murwi",
      latitude: -2.88519,
      longitude: 29.20171,
    },
    {
      name: "Hangar De La Bpae)",
      province: "Cibitoke",
      commune: "Murwi",
      zone: "Murwi",
      latitude: -2.88534,
      longitude: 29.20199,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Cibitoke",
      commune: "Murwi",
      zone: "Buzirasazi",
      latitude: -2.96017,
      longitude: 29.33396,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Cibitoke",
      commune: "Murwi",
      zone: "Buhayira",
      latitude: -2.95635,
      longitude: 29.29282,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Cibitoke",
      commune: "Murwi",
      zone: "Ngoma",
      latitude: -2.91065,
      longitude: 29.25513,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Cibitoke",
      commune: "Murwi",
      zone: "Buhindo",
      latitude: -2.81408,
      longitude: 29.1881,
    },
    {
      name: "HANGAR communal kugitega",
      province: "Gitega",
      commune: "Itaba",
      zone: "Gihamagara",
      latitude: -3.62904,
      longitude: 30.03401,
    },
    {
      name: "SALLE ZONALE KANYINYA",
      province: "Gitega",
      commune: "Itaba",
      zone: "Itaba",
      latitude: -3.65377,
      longitude: 30.02135,
    },
    {
      name: "Hangar Rutegama Rural",
      province: "Gitega",
      commune: "Gitega",
      zone: "Gitega Rural",
      latitude: -3.41661,
      longitude: 29.93812,
    },
    {
      name: "HANGAR REGIONAL DE DESENGORGEMENT CHEZ MELENCE DE GITEGA",
      province: "Gitega",
      commune: "Gitega",
      zone: "Gitega Rural",
      latitude: -3.43477,
      longitude: 29.94784,
    },
    {
      name: "HANGAR REGIONAL DE DESENGORGEMENT CHEZ SHOPPING DE GITEGA",
      province: "Gitega",
      commune: "Gitega",
      zone: "Gitega Urbain",
      latitude: -3.42158,
      longitude: 29.91793,
    },
    {
      name: "HANGAR REGIONAL DE GITEGA BWOGA ",
      province: "Gitega",
      commune: "Gitega",
      zone: "Gitega Urbain",
      latitude: -3.41347,
      longitude: 29.89965,
    },
    {
      name: "Cem Mubuga",
      province: "Gitega",
      commune: "Gitega",
      zone: "Mubuga",
      latitude: -3.41596,
      longitude: 30.02611,
    },
    {
      name: "SALLE POLYVALENTE DE MUNGWA",
      province: "Gitega",
      commune: "Gitega",
      zone: "Mungwa",
      latitude: -3.45269,
      longitude: 29.88159,
    },
    {
      name: "Salle Zonale",
      province: "Gitega",
      commune: "Itaba",
      zone: "Buhevyi",
      latitude: -3.5358,
      longitude: 30.04892,
    },
    {
      name: "CM. KIDONZI",
      province: "Gitega",
      commune: "Itaba",
      zone: "Gihamagara",
      latitude: -3.61267,
      longitude: 30.04099,
    },
    {
      name: "HANGAR  COMMUNAL",
      province: "Gitega",
      commune: "Bukirasazi",
      zone: "Bukirasazi",
      latitude: -3.70085,
      longitude: 29.96554,
    },
    {
      name: "HANGAR  ZONAL",
      province: "Gitega",
      commune: "Bukirasazi",
      zone: "Kangozi",
      latitude: -3.71704,
      longitude: 29.96359,
    },
    {
      name: "HANGAR DE STOCKAGE BUGENDANA",
      province: "Gitega",
      commune: "Bugendana",
      zone: "Bugendana",
      latitude: -3.23175,
      longitude: 29.91649,
    },
    {
      name: "STOCK DE LA COPERATIVE CISHWA",
      province: "Gitega",
      commune: "Bugendana",
      zone: "Bugendana",
      latitude: -3.22284,
      longitude: 29.94764,
    },
    {
      name: "Salle Petit Seminaire Mugera",
      province: "Gitega",
      commune: "Bugendana",
      zone: "Mugera",
      latitude: -3.32335,
      longitude: 29.96749,
    },
    {
      name: "Hangar Cooperative Mutoyi",
      province: "Gitega",
      commune: "Bugendana",
      zone: "Mutoyi",
      latitude: -3.21477,
      longitude: 29.9792,
    },
    {
      name: "HANGAR COOPERATIVE KIVUVU",
      province: "Gitega",
      commune: "Bugendana",
      zone: "Mutoyi",
      latitude: -3.25812,
      longitude: 29.98709,
    },
    {
      name: "Hangar Cem",
      province: "Gitega",
      commune: "Giheta",
      zone: "Kiriba",
      latitude: -3.35815,
      longitude: 29.97432,
    },
    {
      name: "Hangar Zonal Bitare",
      province: "Gitega",
      commune: "Bugendana",
      zone: "Bitare",
      latitude: -3.27679,
      longitude: 29.85906,
    },
    {
      name: "HANGAR ZONE MUGARURO",
      province: "Gitega",
      commune: "Gishubi",
      zone: "Mugaruro",
      latitude: -3.59058,
      longitude: 29.90853,
    },
    {
      name: "Hangar Cem Ruhande",
      province: "Gitega",
      commune: "Gishubi",
      zone: "Nyabiraba",
      latitude: -3.6265,
      longitude: 29.8626,
    },
    {
      name: "HANGAR PAROISSIALE ",
      province: "Gitega",
      commune: "Gishubi",
      zone: "Nyabitanga",
      latitude: -3.68039,
      longitude: 29.87774,
    },
    {
      name: "CEM RWEZA",
      province: "Gitega",
      commune: "Ryansoro",
      zone: "Rweza",
      latitude: -3.64867,
      longitude: 29.77596,
    },
    {
      name: "CEM NDAVA",
      province: "Gitega",
      commune: "Ryansoro",
      zone: "Mahwa",
      latitude: -3.74713,
      longitude: 29.8054,
    },
    {
      name: "HANGAR  ZONAL",
      province: "Gitega",
      commune: "Ryansoro",
      zone: "Kavumu",
      latitude: -3.66891,
      longitude: 29.84888,
    },
    {
      name: "Hangar Commune Giheta",
      province: "Gitega",
      commune: "Giheta",
      zone: "Giheta",
      latitude: -3.35573,
      longitude: 29.85963,
    },
    {
      name: "Ceds Bukinga",
      province: "Gitega",
      commune: "Giheta",
      zone: "Kabanga",
      latitude: -3.29725,
      longitude: 29.87529,
    },
    {
      name: "HANGAR  COMMUNAL ",
      province: "Gitega",
      commune: "Buraza",
      zone: "Buraza",
      latitude: -3.74683,
      longitude: 29.90271,
    },
    {
      name: "SALLE COMMUNALE BUTEZI",
      province: "Gitega",
      commune: "Buraza",
      zone: "Butezi",
      latitude: -3.78467,
      longitude: 29.95999,
    },
    {
      name: "HANGAR  ZONAL  MAHONDA",
      province: "Gitega",
      commune: "Buraza",
      zone: "Mahonda",
      latitude: -3.72867,
      longitude: 29.87026,
    },
    {
      name: "Hangar Cooperative Mboneramiryango",
      province: "Gitega",
      commune: "Giheta",
      zone: "Kabanga",
      latitude: -3.29257,
      longitude: 29.80165,
    },
    {
      name: "HANGAR REGIONAL DE DESENGORGEMENT DE GIHUGA",
      province: "Gitega",
      commune: "Giheta",
      zone: "Kabanga",
      latitude: -3.29078,
      longitude: 29.84063,
    },
    {
      name: "Ecofo Bigera,Salle Y Amahoro-",
      province: "Gitega",
      commune: "Mutaho",
      zone: "Mutaho",
      latitude: -3.15744,
      longitude: 29.86098,
    },
    {
      name: "Salle Zonale  Et Salle Paroissi",
      province: "Gitega",
      commune: "Mutaho",
      zone: "Rwisabi",
      latitude: -3.09531,
      longitude: 29.86941,
    },
    {
      name: "Hangar Makebuko",
      province: "Gitega",
      commune: "Makebuko",
      zone: "Makebuko",
      latitude: -3.60063,
      longitude: 29.99551,
    },
    {
      name: "Ceem Rwezamenyo",
      province: "Gitega",
      commune: "Makebuko",
      zone: "Maramvya",
      latitude: -3.54675,
      longitude: 29.97764,
    },
    {
      name: "Hangar Bugumbasha",
      province: "Gitega",
      commune: "Makebuko",
      zone: "Murenda",
      latitude: -3.64106,
      longitude: 29.97809,
    },
    {
      name: "HANGAR  COMMUNAL ",
      province: "Gitega",
      commune: "Nyarusange",
      zone: "Bukoro",
      latitude: -3.54401,
      longitude: 29.86832,
    },
    {
      name: "SALLE ECOFO",
      province: "Gitega",
      commune: "Nyarusange",
      zone: "Murambi",
      latitude: -3.61756,
      longitude: 29.8281,
    },
    {
      name: "HANGAR  COMMUNAL ",
      province: "Gitega",
      commune: "Nyarusange",
      zone: "Nyarusange",
      latitude: -3.57685,
      longitude: 29.80798,
    },
    {
      name: "Hangar Cem",
      province: "Karusi",
      commune: "Mutumba",
      zone: "Bibara",
      latitude: -3.19849,
      longitude: 30.24746,
    },
    {
      name: "Hangar Centre En Face Du Marché",
      province: "Karusi",
      commune: "Mutumba",
      zone: "Gisimbawaga",
      latitude: -3.19825,
      longitude: 30.22573,
    },
    {
      name: "Gatonde Centre",
      province: "Karusi",
      commune: "Nyabikere",
      zone: "Gatonde",
      latitude: -3.25404,
      longitude: 30.18564,
    },
    {
      name: "Hangar En Face Du Marché /Prodefi",
      province: "Karusi",
      commune: "Mutumba",
      zone: "Gisimbawaga",
      latitude: -3.20033,
      longitude: 30.22537,
    },
    {
      name: "Cem Rwandagaro",
      province: "Karusi",
      commune: "Nyabikere",
      zone: "Maramvya",
      latitude: -3.27802,
      longitude: 30.11727,
    },
    {
      name: "Hangar Gisimbawaga Centre--Prodefi",
      province: "Karusi",
      commune: "Mutumba",
      zone: "Gisimbawaga",
      latitude: -3.16037,
      longitude: 30.22051,
    },
    {
      name: "Hangar Nyabibuye",
      province: "Karusi",
      commune: "Shombo",
      zone: "Nyabibuye",
      latitude: -3.33967,
      longitude: 30.02175,
    },
    {
      name: "Hangar Muzenga",
      province: "Karusi",
      commune: "Gihogazi",
      zone: "Rusamaza",
      latitude: -3.17164,
      longitude: 30.01863,
    },
    {
      name: "Hangar Kivoga",
      province: "Karusi",
      commune: "Gihogazi",
      zone: "Munanira",
      latitude: -3.16458,
      longitude: 29.92864,
    },
    {
      name: "Hangar Nyarurambi",
      province: "Karusi",
      commune: "Shombo",
      zone: "Nyarurambi",
      latitude: -3.32879,
      longitude: 30.05733,
    },
    {
      name: "Hangar Cem Shombo",
      province: "Karusi",
      commune: "Shombo",
      zone: "Rusi",
      latitude: -3.25318,
      longitude: 30.04813,
    },
    {
      name: "Hangar Cooperative Kindobwe",
      province: "Karusi",
      commune: "Nyabikere",
      zone: "Rugwiza",
      latitude: -3.26457,
      longitude: 30.1191,
    },
    {
      name: "Rugwiza Centre",
      province: "Karusi",
      commune: "Nyabikere",
      zone: "Rugwiza",
      latitude: -3.20516,
      longitude: 30.13527,
    },
    {
      name: "Hangar Gatabo",
      province: "Karusi",
      commune: "Shombo",
      zone: "Nyabibuye",
      latitude: -3.31308,
      longitude: 30.025,
    },
    {
      name: "Hangar Rusi  Cadi",
      province: "Karusi",
      commune: "Shombo",
      zone: "Rusi",
      latitude: -3.19891,
      longitude: 30.06633,
    },
    {
      name: "Hangar Mugogo",
      province: "Karusi",
      commune: "Gihogazi",
      zone: "Gihogazi",
      latitude: -3.06928,
      longitude: 29.96565,
    },
    {
      name: "Hangar  Kamahoro",
      province: "Karusi",
      commune: "Buhiga",
      zone: "Rutonganikwa",
      latitude: -3.03604,
      longitude: 30.21206,
    },
    {
      name: "Hangar Rwingoma",
      province: "Karusi",
      commune: "Buhiga",
      zone: "Buhiga",
      latitude: -3.04758,
      longitude: 30.15878,
    },
    {
      name: "Hangar De Bihemba",
      province: "Karusi",
      commune: "Bugenyuzi",
      zone: "Rugazi",
      latitude: -3.05769,
      longitude: 30.06435,
    },
    {
      name: "Hangar Bugendana",
      province: "Karusi",
      commune: "Bugenyuzi",
      zone: "Bugenyuzi",
      latitude: -3.09909,
      longitude: 30.05883,
    },
    {
      name: "Hangar Kanazi",
      province: "Karusi",
      commune: "Bugenyuzi",
      zone: "Masabo",
      latitude: -3.11826,
      longitude: 30.04176,
    },
    {
      name: "Hangar De Mugoboka",
      province: "Karusi",
      commune: "Bugenyuzi",
      zone: "Masabo",
      latitude: -3.10793,
      longitude: 30.06974,
    },
    {
      name: "Hangar De Masabo",
      province: "Karusi",
      commune: "Bugenyuzi",
      zone: "Masabo",
      latitude: -3.14938,
      longitude: 30.07421,
    },
    {
      name: "Hangar  De Kidahwe",
      province: "Karusi",
      commune: "Bugenyuzi",
      zone: "Rugazi",
      latitude: -3.01071,
      longitude: 30.01507,
    },
    {
      name: "Hangar Cem Karusi",
      province: "Karusi",
      commune: "Buhiga",
      zone: "Buhinyuza",
      latitude: -3.10032,
      longitude: 30.15541,
    },
    {
      name: "Hangar Rudaraza",
      province: "Karusi",
      commune: "Buhiga",
      zone: "Rutonganikwa",
      latitude: -3.06223,
      longitude: 30.21162,
    },
    {
      name: "Hangar Ramba",
      province: "Karusi",
      commune: "Gihogazi",
      zone: "Gihogazi",
      latitude: -3.11825,
      longitude: 30.01558,
    },
    {
      name: "HANGAR DE DESANGORGEMENT COMMUNAL GITARAMUKA",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Gitaramuka",
      latitude: -2.97923,
      longitude: 30.17487,
    },
    {
      name: "Hangar Kibumbwe",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Ntunda",
      latitude: -3.01824,
      longitude: 30.07966,
    },
    {
      name: "Hangar Nzibariba",
      province: "Karusi",
      commune: "Buhiga",
      zone: "Buhiga",
      latitude: -3.00153,
      longitude: 30.1928,
    },
    {
      name: "Hangar Centre Jeunes",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Gitaramuka",
      latitude: -2.98052,
      longitude: 30.17415,
    },
    {
      name: "Hangar Croix Rouge",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Gitaramuka",
      latitude: -2.98074,
      longitude: 30.17506,
    },
    {
      name: "Hangar Nyaruhinda",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Nyaruhinda",
      latitude: -2.96174,
      longitude: 30.22965,
    },
    {
      name: "Hangar En Soko Du Coopera.Gitaramuka",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Gitaramuka",
      latitude: -2.97815,
      longitude: 30.16754,
    },
    {
      name: "Hangar Paivab",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Gitaramuka",
      latitude: -2.98078,
      longitude: 30.17552,
    },
    {
      name: "Hangar Ntunda",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Ntunda",
      latitude: -2.99539,
      longitude: 30.12566,
    },
    {
      name: "Hangar Cirambo",
      province: "Karusi",
      commune: "Gitaramuka",
      zone: "Nyaruhinda",
      latitude: -2.93547,
      longitude: 30.18799,
    },
    {
      name: "HANGAR DE DESANGORGEMENT CEM BUGENYUZI",
      province: "Karusi",
      commune: "Bugenyuzi",
      zone: "Bugenyuzi",
      latitude: -3.09335,
      longitude: 30.06346,
    },
    {
      name: "STOCK DE DESENGORGEMENT MOTEL KARUSI",
      province: "Karusi",
      commune: "Buhiga",
      zone: "Buhinyuza",
      latitude: -3.10569,
      longitude: 30.16909,
    },
    {
      name: "HANGAR DE DESENGORGEMENT BPAE KARUSI",
      province: "Karusi",
      commune: "Buhiga",
      zone: "Buhinyuza",
      latitude: -3.09993,
      longitude: 30.16109,
    },
    {
      name: "STOCK ZONAL JENE",
      province: "Kayanza",
      commune: "Kabarore",
      zone: "Jene",
      latitude: -2.84947,
      longitude: 29.62581,
    },
    {
      name: "HANGAR ZONE RWEGURA",
      province: "Kayanza",
      commune: "Muruta",
      zone: "Rwegura",
      latitude: -2.9216,
      longitude: 29.58745,
    },
    {
      name: "STOCK NKONGE",
      province: "Kayanza",
      commune: "Muruta",
      zone: "Nkonge",
      latitude: -2.98676,
      longitude: 29.59835,
    },
    {
      name: "HANGAR MURUTA",
      province: "Kayanza",
      commune: "Muruta",
      zone: "Muruta",
      latitude: -2.95266,
      longitude: 29.59765,
    },
    {
      name: "HANGAR MURIMA",
      province: "Kayanza",
      commune: "Kayanza",
      zone: "Murima",
      latitude: -2.891,
      longitude: 29.60839,
    },
    {
      name: "Hangar Gatwaro",
      province: "Kayanza",
      commune: "Kayanza",
      zone: "Kayanza",
      latitude: -2.93231,
      longitude: 29.63481,
    },
    {
      name: "Lco Kabuye",
      province: "Kayanza",
      commune: "Kayanza",
      zone: "Kabuye",
      latitude: -2.89674,
      longitude: 29.6672,
    },
    {
      name: "Lco Mudahara",
      province: "Kayanza",
      commune: "Kayanza",
      zone: "Nyabihogo",
      latitude: -2.99703,
      longitude: 29.63316,
    },
    {
      name: "Bureau Zonal Kabuye",
      province: "Kayanza",
      commune: "Matongo",
      zone: "Kabuye",
      latitude: -3.03132,
      longitude: 29.59932,
    },
    {
      name: "ZONE KABARORE",
      province: "Kayanza",
      commune: "Kabarore",
      zone: "Kabarore",
      latitude: -2.84976,
      longitude: 29.53907,
    },
    {
      name: "HANGAR BANGA",
      province: "Kayanza",
      commune: "Matongo",
      zone: "Banga",
      latitude: -3.12037,
      longitude: 29.6105,
    },
    {
      name: "Cds Burarana",
      province: "Kayanza",
      commune: "Matongo",
      zone: "Burarana",
      latitude: -3.08222,
      longitude: 29.64314,
    },
    {
      name: "Echoppe Marche Burengo",
      province: "Kayanza",
      commune: "Matongo",
      zone: "Ruganza",
      latitude: -3.06029,
      longitude: 29.61212,
    },
    {
      name: "Hangar Nyabibuye",
      province: "Kayanza",
      commune: "Butaganzwa/Kayanza",
      zone: "Nyabibuye",
      latitude: -3.10783,
      longitude: 29.69742,
    },
    {
      name: "MUCERI WACU RWIRA",
      province: "Kayanza",
      commune: "Butaganzwa/Kayanza",
      zone: "Butaganzwa",
      latitude: -3.10402,
      longitude: 29.72269,
    },
    {
      name: "NINGA/BUMBA",
      province: "Kayanza",
      commune: "Butaganzwa/Kayanza",
      zone: "Ninga",
      latitude: -3.11157,
      longitude: 29.6933,
    },
    {
      name: "Hangar Centre Jeunes",
      province: "Kayanza",
      commune: "Gatara",
      zone: "Ngoro",
      latitude: -3.03879,
      longitude: 29.68073,
    },
    {
      name: "HANGAR NYARURAMBI/GATARA",
      province: "Kayanza",
      commune: "Gatara",
      zone: "Gatara",
      latitude: -2.99565,
      longitude: 29.65615,
    },
    {
      name: "CEM GAHOMBO ",
      province: "Kayanza",
      commune: "Gahombo",
      zone: "Gahombo",
      latitude: -2.97038,
      longitude: 29.73505,
    },
    {
      name: "CEM KIROMBWE",
      province: "Kayanza",
      commune: "Gahombo",
      zone: "Nzewe",
      latitude: -3.05021,
      longitude: 29.73794,
    },
    {
      name: "STOCK ZONAL MUBOGORA",
      province: "Kayanza",
      commune: "Muhanga",
      zone: "Muhanga",
      latitude: -3.06844,
      longitude: 29.81736,
    },
    {
      name: "CEM GAHETA",
      province: "Kayanza",
      commune: "Rango",
      zone: "Gaheta",
      latitude: -3.14855,
      longitude: 29.7602,
    },
    {
      name: "CEM GIKOMERO",
      province: "Kayanza",
      commune: "Rango",
      zone: "Gikomero",
      latitude: -3.15162,
      longitude: 29.82733,
    },
    {
      name: "GATARE",
      province: "Kayanza",
      commune: "Rango",
      zone: "Kabuye",
      latitude: -3.18227,
      longitude: 29.71235,
    },
    {
      name: "Cds Gihororo",
      province: "Kayanza",
      commune: "Rango",
      zone: "Rango",
      latitude: -3.10573,
      longitude: 29.80321,
    },
    {
      name: "HANGAR MIBAZI",
      province: "Kayanza",
      commune: "Muhanga",
      zone: "Maramvya",
      latitude: -3.02096,
      longitude: 29.76697,
    },
    {
      name: "HANGAR MUHANGA NGOMA",
      province: "Kayanza",
      commune: "Muhanga",
      zone: "Muhanga",
      latitude: -3.02822,
      longitude: 29.8205,
    },
    {
      name: "Hangar Muhanga",
      province: "Kayanza",
      commune: "Muhanga",
      zone: "Muhanga",
      latitude: -3.02871,
      longitude: 29.84153,
    },
    {
      name: "HANGAR MARIDADI/GLOBAL PORT",
      province: "Kayanza",
      commune: "Kayanza",
      zone: "Kabuye",
      latitude: -2.90284,
      longitude: 29.70976,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Ntega",
      zone: "Murungurira",
      latitude: -2.56878,
      longitude: 30.02686,
    },
    {
      name: "Hangar Gisota",
      province: "Kirundo",
      commune: "Ntega",
      zone: "Mugendo",
      latitude: -2.56426,
      longitude: 29.99584,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Ntega",
      zone: "Ntega",
      latitude: -2.60786,
      longitude: 29.99258,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Ntega",
      zone: "Rushubije",
      latitude: -2.63754,
      longitude: 30.0429,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Vumbi",
      zone: "Bukuba",
      latitude: -2.69761,
      longitude: 30.05725,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Vumbi",
      zone: "Cendajuru",
      latitude: -2.68525,
      longitude: 30.13326,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Gitobe",
      zone: "Gitobe",
      latitude: -2.6473,
      longitude: 30.20144,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Gitobe",
      zone: "Shore",
      latitude: -2.60051,
      longitude: 30.27581,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Gitobe",
      zone: "Baziro",
      latitude: -2.63275,
      longitude: 30.25649,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bwambarangwe",
      zone: "Mukenke",
      latitude: -2.59099,
      longitude: 30.31273,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bwambarangwe",
      zone: "Mukenke",
      latitude: -2.5571,
      longitude: 30.34139,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bwambarangwe",
      zone: "Bugorora",
      latitude: -2.64504,
      longitude: 30.30862,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bwambarangwe",
      zone: "Buhoro",
      latitude: -2.49759,
      longitude: 30.37926,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bwambarangwe",
      zone: "Kimeza",
      latitude: -2.5405,
      longitude: 30.37457,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bwambarangwe",
      zone: "Kimeza",
      latitude: -2.57637,
      longitude: 30.39367,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kiyonza",
      latitude: -2.37353,
      longitude: 30.01566,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kiyonza",
      latitude: -2.35442,
      longitude: 29.98584,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kiyonza",
      latitude: -2.40284,
      longitude: 30.00953,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kigina",
      latitude: -2.43307,
      longitude: 30.03556,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kigina",
      latitude: -2.43795,
      longitude: 30.02856,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kigina",
      latitude: -2.44882,
      longitude: 30.03264,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kigoma",
      latitude: -2.4904,
      longitude: 30.02863,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kigoma",
      latitude: -2.44864,
      longitude: 30.06439,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Bugabira",
      zone: "Kigoma",
      latitude: -2.47077,
      longitude: 30.07628,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Kirundo",
      zone: "Ceru",
      latitude: -2.51009,
      longitude: 30.08644,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Busoni",
      zone: "Mukerwa",
      latitude: -2.60629,
      longitude: 30.19148,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Busoni",
      zone: "Murore",
      latitude: -2.52247,
      longitude: 30.26705,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Busoni",
      zone: "Nyagisozi",
      latitude: -2.47324,
      longitude: 30.33848,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Busoni",
      zone: "Gatare",
      latitude: -2.44052,
      longitude: 30.26424,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Busoni",
      zone: "Gisenyi",
      latitude: -2.40252,
      longitude: 30.21809,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Kirundo",
      zone: "Kirundo Rural",
      latitude: -2.56182,
      longitude: 30.12458,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Kirundo",
      zone: "Kirundo Rural",
      latitude: -2.54599,
      longitude: 30.12511,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Kirundo",
      zone: "Kirundo Centre",
      latitude: -2.58955,
      longitude: 30.09051,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Kirundo",
      zone: "Kirundo Centre",
      latitude: -2.5864,
      longitude: 30.08741,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Kirundo",
      zone: "Kirundo Rural",
      latitude: -2.55093,
      longitude: 30.15042,
    },
    {
      name: "Salle Communal",
      province: "Kirundo",
      commune: "Vumbi",
      zone: "Vumbi",
      latitude: -2.6991,
      longitude: 30.10451,
    },
    {
      name: "STOCKAGE DE DESENGORGEMENT DE KAYOGORO",
      province: "Makamba",
      commune: "Kayogoro",
      zone: "Kayogoro",
      latitude: -4.12297,
      longitude: 29.94426,
    },
    {
      name: "HANGAR ZONAL KAYOGORO",
      province: "Makamba",
      commune: "Kayogoro",
      zone: "Kayogoro",
      latitude: -4.12912,
      longitude: 29.94294,
    },
    {
      name: "HANGAR DE LA COOPÉRATIVE ZIGANYUMWIMBUDE GATABO",
      province: "Makamba",
      commune: "Kayogoro",
      zone: "Gatabo",
      latitude: -4.08543,
      longitude: 30.10792,
    },
    {
      name: "HANGAR ZONAL MUGENI",
      province: "Makamba",
      commune: "Kayogoro",
      zone: "Mugeni",
      latitude: -4.11721,
      longitude: 30.05485,
    },
    {
      name: "HANGAR ZONAL DE BIGINA",
      province: "Makamba",
      commune: "Kayogoro",
      zone: "Bigina",
      latitude: -4.2235,
      longitude: 29.99185,
    },
    {
      name: "HANGAR ZONAL DE DUNGA ",
      province: "Makamba",
      commune: "Kayogoro",
      zone: "Dunga",
      latitude: -4.18881,
      longitude: 29.93877,
    },
    {
      name: "HANGAR ZONAL DE KIYANGE",
      province: "Makamba",
      commune: "Kibago",
      zone: "Kiyange",
      latitude: -4.22103,
      longitude: 29.92502,
    },
    {
      name: "HANGAR ZONAL DE BUKEYE ",
      province: "Makamba",
      commune: "Kibago",
      zone: "Bukeye",
      latitude: -4.30424,
      longitude: 29.91475,
    },
    {
      name: "HANGAR ZONAL DE MUSENYI ",
      province: "Makamba",
      commune: "Mabanda",
      zone: "Gitara",
      latitude: -4.37029,
      longitude: 29.7621,
    },
    {
      name: "HANGAR DE LA ZONE KIBAGO ",
      province: "Makamba",
      commune: "Kibago",
      zone: "Kibago",
      latitude: -4.27242,
      longitude: 29.85081,
    },
    {
      name: "HANGAR DE GIKURAZO ",
      province: "Makamba",
      commune: "Mabanda",
      zone: "Mabanda",
      latitude: -4.21801,
      longitude: 29.82713,
    },
    {
      name: "HANGAR DE STOCKAGE DE RUTEGAMA ",
      province: "Makamba",
      commune: "Vugizo",
      zone: "Gishiha",
      latitude: -4.11348,
      longitude: 29.72243,
    },
    {
      name: "HANGAR COMMUNAUTAIRE DE NDOBA",
      province: "Makamba",
      commune: "Vugizo",
      zone: "Mpinga",
      latitude: -4.14569,
      longitude: 29.67274,
    },
    {
      name: "HANGAR ZONAL DE VUGIZO",
      province: "Makamba",
      commune: "Vugizo",
      zone: "Vugizo",
      latitude: -4.19798,
      longitude: 29.70495,
    },
    {
      name: "HANGAR ZONAL DE NYANGE",
      province: "Makamba",
      commune: "Makamba",
      zone: "Nyange",
      latitude: -4.14681,
      longitude: 29.87339,
    },
    {
      name: "HANGAR ZONAL MAKAMBA",
      province: "Makamba",
      commune: "Makamba",
      zone: "Makamba",
      latitude: -4.13341,
      longitude: 29.80554,
    },
    {
      name: "HANGAR ZONAL DE NYANZA LAC ",
      province: "Makamba",
      commune: "Nyanza-Lac",
      zone: "Muyange",
      latitude: -4.30645,
      longitude: 29.68567,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Kiganda",
      zone: "Gatabo",
      latitude: -3.28442,
      longitude: 29.70232,
    },
    {
      name: "Hangar OMC zone Buhangura",
      province: "Muramvya",
      commune: "Mbuye",
      zone: "Buhangura",
      latitude: -3.22294,
      longitude: 29.72769,
    },
    {
      name: "Salle Zonale",
      province: "Muramvya",
      commune: "Mbuye",
      zone: "Gasura",
      latitude: -3.23073,
      longitude: 29.80151,
    },
    {
      name: "Hangar du centre des metiers de kirembera ",
      province: "Muramvya",
      commune: "Mbuye",
      zone: "Mbuye",
      latitude: -3.24989,
      longitude: 29.69689,
    },
    {
      name: "Hangar communal",
      province: "Muramvya",
      commune: "Mbuye",
      zone: "Mbuye",
      latitude: -3.23048,
      longitude: 29.72094,
    },
    {
      name: "Salles de classe du centre des metiers ",
      province: "Muramvya",
      commune: "Rutegama",
      zone: "Rutegama",
      latitude: -3.31016,
      longitude: 29.75138,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Rutegama",
      zone: "Mushikamo",
      latitude: -3.33263,
      longitude: 29.70503,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Kiganda",
      zone: "Kanyami",
      latitude: -3.40359,
      longitude: 29.66088,
    },
    {
      name: "Hangar PRODEFI",
      province: "Muramvya",
      commune: "Kiganda",
      zone: "Kiganda",
      latitude: -3.35129,
      longitude: 29.67013,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Muramvya",
      zone: "Bugarama",
      latitude: -3.28527,
      longitude: 29.54843,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Muramvya",
      zone: "Muramvya",
      latitude: -3.26729,
      longitude: 29.62289,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Muramvya",
      zone: "Shombo",
      latitude: -3.3246,
      longitude: 29.62095,
    },
    {
      name: "Hangar Rwasazi du BPEAE de desengorgement",
      province: "Muramvya",
      commune: "Muramvya",
      zone: "Muramvya",
      latitude: -3.26324,
      longitude: 29.60904,
    },
    {
      name: "Hangar Communal",
      province: "Muramvya",
      commune: "Bukeye",
      zone: "Bukeye",
      latitude: -3.19262,
      longitude: 29.62908,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Bukeye",
      zone: "Busangana",
      latitude: -3.15397,
      longitude: 29.61717,
    },
    {
      name: "Hangar Zonal",
      province: "Muramvya",
      commune: "Bukeye",
      zone: "Nyarucamo",
      latitude: -3.19592,
      longitude: 29.68083,
    },
    {
      name: "Coop.Muhini Girijambo",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Mugano",
      latitude: -2.84477,
      longitude: 30.34191,
    },
    {
      name: "Lycee Communal",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Giteranyi",
      latitude: -2.84496,
      longitude: 30.34157,
    },
    {
      name: "Rugari 1",
      province: "Muyinga",
      commune: "Muyinga",
      zone: "Rugari",
      latitude: -2.72253,
      longitude: 30.41065,
    },
    {
      name: "STOCK NYARUTONGO",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Giteranyi",
      latitude: -2.53706,
      longitude: 30.45008,
    },
    {
      name: "Rugari 2",
      province: "Muyinga",
      commune: "Muyinga",
      zone: "Rugari",
      latitude: -2.72849,
      longitude: 30.41001,
    },
    {
      name: "Cumba",
      province: "Muyinga",
      commune: "Muyinga",
      zone: "Cumba",
      latitude: -2.92017,
      longitude: 30.30818,
    },
    {
      name: "Cumba Nyamirambo",
      province: "Muyinga",
      commune: "Muyinga",
      zone: "Muyinga",
      latitude: -2.90848,
      longitude: 30.29155,
    },
    {
      name: "HANGAR RUGESE",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Giteranyi",
      latitude: -2.52802,
      longitude: 30.4428,
    },
    {
      name: "Ex Bureau Communal",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Giteranyi",
      latitude: -2.48872,
      longitude: 30.46562,
    },
    {
      name: "Munagano",
      province: "Muyinga",
      commune: "Muyinga",
      zone: "Munagano",
      latitude: -2.79486,
      longitude: 30.38502,
    },
    {
      name: "Cfpp",
      province: "Muyinga",
      commune: "Muyinga",
      zone: "Muyinga",
      latitude: -2.84845,
      longitude: 30.33979,
    },
    {
      name: "Salle Cooperative",
      province: "Muyinga",
      commune: "Muyinga",
      zone: "Muyinga",
      latitude: -2.84481,
      longitude: 30.33983,
    },
    {
      name: "LYCEE COMMUNAL ",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Masaka",
      latitude: -2.35829,
      longitude: 30.42969,
    },
    {
      name: "HANGAR RUKUSHA",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Masaka",
      latitude: -2.37887,
      longitude: 30.44487,
    },
    {
      name: "HANGAR RUZO",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Ruzo",
      latitude: -2.4,
      longitude: 30.43943,
    },
    {
      name: "STOCK KIGWEGWE",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Giteranyi",
      latitude: -2.454,
      longitude: 30.43738,
    },
    {
      name: "STOCK KINYAMI",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Tura",
      latitude: -2.46653,
      longitude: 30.51259,
    },
    {
      name: "HANGAR ECOFO TURA",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Tura",
      latitude: -2.41736,
      longitude: 30.48496,
    },
    {
      name: "STOCK KINANIRA",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Tura",
      latitude: -2.4312,
      longitude: 30.52796,
    },
    {
      name: "STOCK ECOFO GAKONI",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Tura",
      latitude: -2.44372,
      longitude: 30.47918,
    },
    {
      name: "Hangar Kiyanza",
      province: "Muyinga",
      commune: "Mwakiro",
      zone: "Kiyanza",
      latitude: -3.09115,
      longitude: 30.3379,
    },
    {
      name: "Lycee Communal Kiyanza",
      province: "Muyinga",
      commune: "Mwakiro",
      zone: "Kiyanza",
      latitude: -3.0916,
      longitude: 30.33535,
    },
    {
      name: "CEM mwakiro",
      province: "Muyinga",
      commune: "Mwakiro",
      zone: "Mwakiro",
      latitude: -3.12903,
      longitude: 30.29106,
    },
    {
      name: "Hangar garderie",
      province: "Muyinga",
      commune: "Mwakiro",
      zone: "Kiyanza",
      latitude: -3.09049,
      longitude: 30.33655,
    },
    {
      name: "Garderie Rugabano",
      province: "Muyinga",
      commune: "Mwakiro",
      zone: "Rugabano",
      latitude: -3.06187,
      longitude: 30.27934,
    },
    {
      name: "Hangar Rugabano",
      province: "Muyinga",
      commune: "Mwakiro",
      zone: "Rugabano",
      latitude: -3.06495,
      longitude: 30.27751,
    },
    {
      name: "HANGAR STOCK NGATI",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Butarugera",
      latitude: -2.66761,
      longitude: 30.39979,
    },
    {
      name: "HANGAR RABIRO",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Butarugera",
      latitude: -2.64114,
      longitude: 30.39341,
    },
    {
      name: "HANGAR TANGARA",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Butarugera",
      latitude: -2.6782,
      longitude: 30.35603,
    },
    {
      name: "HANGAR MANGOMA",
      province: "Muyinga",
      commune: "Giteranyi",
      zone: "Mugano",
      latitude: -2.58675,
      longitude: 30.42037,
    },
    {
      name: "HANGAR MARAMVYA",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Butihinda",
      latitude: -2.77492,
      longitude: 30.31847,
    },
    {
      name: "HANGAR BUTIHINDA",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Butihinda",
      latitude: -2.75256,
      longitude: 30.3085,
    },
    {
      name: "HANGAR MASAKA",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Buvumbi",
      latitude: -2.75546,
      longitude: 30.27514,
    },
    {
      name: "HANGAR NYAMIHONDI",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Buvumbi",
      latitude: -2.76886,
      longitude: 30.23744,
    },
    {
      name: "HANGAR RWAMFU",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Kamaramagambo",
      latitude: -2.7256,
      longitude: 30.36499,
    },
    {
      name: "HANGAR NYAGATOVU",
      province: "Muyinga",
      commune: "Gashoho",
      zone: "Nyagatovu",
      latitude: -2.74247,
      longitude: 30.18607,
    },
    {
      name: "HANGAR CAGIZO",
      province: "Muyinga",
      commune: "Butihinda",
      zone: "Kamaramagambo",
      latitude: -2.67276,
      longitude: 30.306,
    },
    {
      name: "HANGAR BURAMBIRA",
      province: "Muyinga",
      commune: "Gashoho",
      zone: "Burambira",
      latitude: -2.72774,
      longitude: 30.15063,
    },
    {
      name: "HANGAR MUZINGI",
      province: "Muyinga",
      commune: "Gashoho",
      zone: "Gisanze",
      latitude: -2.77665,
      longitude: 30.18547,
    },
    {
      name: "HANGAR MUYANGE",
      province: "Muyinga",
      commune: "Gashoho",
      zone: "Gashoho",
      latitude: -2.81383,
      longitude: 30.12844,
    },
    {
      name: "STOCK EGLISE PENTECOTE BWASARE",
      province: "Muyinga",
      commune: "Gasorwe",
      zone: "Bwasare",
      latitude: -2.83232,
      longitude: 30.19079,
    },
    {
      name: "HANGAR GASORWE",
      province: "Muyinga",
      commune: "Gasorwe",
      zone: "Gasorwe",
      latitude: -2.85223,
      longitude: 30.22043,
    },
    {
      name: "HANGAR ZONE KIREMBA",
      province: "Muyinga",
      commune: "Gasorwe",
      zone: "Kiremba",
      latitude: -2.87109,
      longitude: 30.28507,
    },
    {
      name: "HANGAR JARAMA ",
      province: "Muyinga",
      commune: "Buhinyuza",
      zone: "Jarama",
      latitude: -2.98655,
      longitude: 30.29271,
    },
    {
      name: "HANGAR BUHINYUZA",
      province: "Muyinga",
      commune: "Buhinyuza",
      zone: "Buhinyuza",
      latitude: -2.98887,
      longitude: 30.35607,
    },
    {
      name: "HANGAR GASAVE",
      province: "Muyinga",
      commune: "Buhinyuza",
      zone: "Gasave",
      latitude: -2.96153,
      longitude: 30.39641,
    },
    {
      name: "Hangar Communal",
      province: "Mwaro",
      commune: "Rusaka",
      zone: "Rusaka",
      latitude: -3.44037,
      longitude: 29.63078,
    },
    {
      name: "Salle Communal",
      province: "Mwaro",
      commune: "Rusaka",
      zone: "Makamba",
      latitude: -3.50975,
      longitude: 29.66742,
    },
    {
      name: "Hangar Du Bpeae",
      province: "Mwaro",
      commune: "Bisoro",
      zone: "Bisoro",
      latitude: -3.63641,
      longitude: 29.70786,
    },
    {
      name: "Salle Du Lycée Communal Bikanka",
      province: "Mwaro",
      commune: "Bisoro",
      zone: "Kanka",
      latitude: -3.59936,
      longitude: 29.7548,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Mwaro",
      commune: "Bisoro",
      zone: "Rorero",
      latitude: -3.59736,
      longitude: 29.70959,
    },
    {
      name: "HANGAR ATEKI",
      province: "Mwaro",
      commune: "Gisozi",
      zone: "Gisozi",
      latitude: -3.58489,
      longitude: 29.67049,
    },
    {
      name: "Hangar Zonal",
      province: "Mwaro",
      commune: "Gisozi",
      zone: "Nyakararo",
      latitude: -3.5282,
      longitude: 29.61318,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Mwaro",
      commune: "Kayokwe",
      zone: "Gatwe",
      latitude: -3.56249,
      longitude: 29.73107,
    },
    {
      name: "Salle Communal",
      province: "Mwaro",
      commune: "Kayokwe",
      zone: "Kayokwe",
      latitude: -3.52829,
      longitude: 29.73766,
    },
    {
      name: "Salle Communal",
      province: "Mwaro",
      commune: "Kayokwe",
      zone: "Muyebe",
      latitude: -3.50154,
      longitude: 29.78157,
    },
    {
      name: "Salle du centre des metiers de Fota",
      province: "Mwaro",
      commune: "Ndava",
      zone: "Buziracanda",
      latitude: -3.44253,
      longitude: 29.70382,
    },
    {
      name: "Hangar De La Zone Ndava)",
      province: "Mwaro",
      commune: "Ndava",
      zone: "Ndava",
      latitude: -3.34093,
      longitude: 29.79451,
    },
    {
      name: "Hangar Nyabibugu",
      province: "Mwaro",
      commune: "Nyabihanga",
      zone: "Kibungere",
      latitude: -3.42243,
      longitude: 29.82572,
    },
    {
      name: "Hangar Zonal",
      province: "Mwaro",
      commune: "Nyabihanga",
      zone: "Munago",
      latitude: -3.49742,
      longitude: 29.83527,
    },
    {
      name: "Cooperative populaire Mbogora",
      province: "Mwaro",
      commune: "Nyabihanga",
      zone: "Muyange",
      latitude: -3.45708,
      longitude: 29.76856,
    },
    {
      name: "Salle Communal",
      province: "Mwaro",
      commune: "Nyabihanga",
      zone: "Nyabihanga",
      latitude: -3.46966,
      longitude: 29.8072,
    },
    {
      name: "Hangar du centre des metiers",
      province: "Mwaro",
      commune: "Nyabihanga",
      zone: "Nyabihanga",
      latitude: -3.47218,
      longitude: 29.8101,
    },
    {
      name: "Salle De Classe",
      province: "Ngozi",
      commune: "Marangara",
      zone: "Marangara",
      latitude: -2.74556,
      longitude: 29.99281,
    },
    {
      name: "Hangar Prodema",
      province: "Ngozi",
      commune: "Marangara",
      zone: "Giheta",
      latitude: -2.7318,
      longitude: 29.96234,
    },
    {
      name: "Cem",
      province: "Ngozi",
      commune: "Gashikanwa",
      zone: "Gashikanwa",
      latitude: -2.91466,
      longitude: 29.89321,
    },
    {
      name: "Cem Kiremera",
      province: "Ngozi",
      commune: "Kiremba",
      zone: "Gakere",
      latitude: -2.86739,
      longitude: 30.00446,
    },
    {
      name: "Hangar Publique",
      province: "Ngozi",
      commune: "Marangara",
      zone: "Cindonyi",
      latitude: -2.69742,
      longitude: 29.98196,
    },
    {
      name: "Hangarcooperativ",
      province: "Ngozi",
      commune: "Marangara",
      zone: "Nyamugari",
      latitude: -2.75587,
      longitude: 29.93292,
    },
    {
      name: "Hangar Zonal",
      province: "Ngozi",
      commune: "Kiremba",
      zone: "Bugina",
      latitude: -2.82394,
      longitude: 30.05396,
    },
    {
      name: "Kiremba chef lieu commune",
      province: "Ngozi",
      commune: "Kiremba",
      zone: "Kiremba",
      latitude: -2.81787,
      longitude: 29.98416,
    },
    {
      name: "Hangar zone Musasa",
      province: "Ngozi",
      commune: "Kiremba",
      zone: "Musasa",
      latitude: -2.83582,
      longitude: 30.07868,
    },
    {
      name: "Hangar Commune",
      province: "Ngozi",
      commune: "Gashikanwa",
      zone: "Gatobo",
      latitude: -2.86877,
      longitude: 29.9354,
    },
    {
      name: "Hangar Commune",
      province: "Ngozi",
      commune: "Gashikanwa",
      zone: "Ngoma",
      latitude: -2.86313,
      longitude: 29.88881,
    },
    {
      name: "Hangar Communal",
      province: "Ngozi",
      commune: "Ruhororo",
      zone: "Mubanga",
      latitude: -2.98278,
      longitude: 29.96432,
    },
    {
      name: "Hangar Publique",
      province: "Ngozi",
      commune: "Tangara",
      zone: "Gasezerwa",
      latitude: -2.89654,
      longitude: 30.11028,
    },
    {
      name: "Prodef",
      province: "Ngozi",
      commune: "Tangara",
      zone: "Musenyi",
      latitude: -2.95269,
      longitude: 30.03725,
    },
    {
      name: "Hangar Communal",
      province: "Ngozi",
      commune: "Ruhororo",
      zone: "Ruhororo",
      latitude: -3.05155,
      longitude: 29.88697,
    },
    {
      name: "Hangar Zonal)",
      province: "Ngozi",
      commune: "Tangara",
      zone: "Kananira",
      latitude: -2.93935,
      longitude: 30.12763,
    },
    {
      name: "Hangar De Stockage",
      province: "Ngozi",
      commune: "Tangara",
      zone: "Nyagatovu",
      latitude: -2.85974,
      longitude: 30.16275,
    },
    {
      name: "Hangar Public",
      province: "Ngozi",
      commune: "Tangara",
      zone: "Tangara",
      latitude: -2.91713,
      longitude: 29.9693,
    },
    {
      name: "Hangar Publique",
      province: "Ngozi",
      commune: "Mwumba",
      zone: "Buye",
      latitude: -2.83724,
      longitude: 29.81401,
    },
    {
      name: "Hangar Communal",
      province: "Ngozi",
      commune: "Busiga",
      zone: "Mihigo",
      latitude: -2.85158,
      longitude: 29.74725,
    },
    {
      name: "Hangar En Face Du Marché /Prodefi",
      province: "Ngozi",
      commune: "Busiga",
      zone: "Rukeco",
      latitude: -2.90713,
      longitude: 29.75321,
    },
    {
      name: "Cem",
      province: "Ngozi",
      commune: "Busiga",
      zone: "Rukeco",
      latitude: -2.90575,
      longitude: 29.75342,
    },
    {
      name: "Hangar Zonal)",
      province: "Ngozi",
      commune: "Nyamurenza",
      zone: "Birambi",
      latitude: -2.78752,
      longitude: 29.90304,
    },
    {
      name: "Hangar Cem",
      province: "Ngozi",
      commune: "Nyamurenza",
      zone: "Birambi",
      latitude: -2.78697,
      longitude: 29.90239,
    },
    {
      name: "Hangar Commune",
      province: "Ngozi",
      commune: "Mwumba",
      zone: "Mwumba",
      latitude: -2.86082,
      longitude: 29.79114,
    },
    {
      name: "CEM RWABIRIRO",
      province: "Ngozi",
      commune: "Mwumba",
      zone: "Gatsinda",
      latitude: -2.81033,
      longitude: 29.83043,
    },
    {
      name: "Hangar Ucode",
      province: "Ngozi",
      commune: "Mwumba",
      zone: "Gatsinda",
      latitude: -2.81964,
      longitude: 29.80704,
    },
    {
      name: "HANGAR 3",
      province: "Ngozi",
      commune: "Busiga",
      zone: "Mparamirundi",
      latitude: -2.84446,
      longitude: 29.66863,
    },
    {
      name: "Hangar 2",
      province: "Ngozi",
      commune: "Busiga",
      zone: "Mparamirundi",
      latitude: -2.84303,
      longitude: 29.66141,
    },
    {
      name: "Hangar Mugende",
      province: "Ngozi",
      commune: "Nyamurenza",
      zone: "Nyamurenza",
      latitude: -2.84708,
      longitude: 29.86649,
    },
    {
      name: "Hangar Kaganda",
      province: "Ngozi",
      commune: "Nyamurenza",
      zone: "Nyamurenza",
      latitude: -2.82557,
      longitude: 29.86621,
    },
    {
      name: "Hangar 1",
      province: "Ngozi",
      commune: "Busiga",
      zone: "Mparamirundi",
      latitude: -2.84131,
      longitude: 29.66029,
    },
    {
      name: "Clac Busiga",
      province: "Ngozi",
      commune: "Busiga",
      zone: "Mihigo",
      latitude: -2.85204,
      longitude: 29.74766,
    },
    {
      name: "Hangar 1+Hangar2",
      province: "Ngozi",
      commune: "Ngozi",
      zone: "Mubuga",
      latitude: -2.9458,
      longitude: 29.83428,
    },
    {
      name: "Hangar 1Coop",
      province: "Ngozi",
      commune: "Ngozi",
      zone: "Mivo",
      latitude: -2.94947,
      longitude: 29.7926,
    },
    {
      name: "Hangar 1Coop",
      province: "Ngozi",
      commune: "Ngozi",
      zone: "Makaba",
      latitude: -2.9923,
      longitude: 29.83198,
    },
    {
      name: "Hangar Bpae+Hangar Prodef",
      province: "Ngozi",
      commune: "Ngozi",
      zone: "Ngozi Urbain",
      latitude: -2.91482,
      longitude: 29.82002,
    },
    {
      name: "Hangar 1 Public",
      province: "Ngozi",
      commune: "Ngozi",
      zone: "Ngozi Rural",
      latitude: -2.90583,
      longitude: 29.79152,
    },
    {
      name: "Hangar De Stockage",
      province: "Ngozi",
      commune: "Ngozi",
      zone: "Mugomera",
      latitude: -2.99866,
      longitude: 29.88159,
    },
    {
      name: "Hangar Cooperativ",
      province: "Ngozi",
      commune: "Mwumba",
      zone: "Buye",
      latitude: -2.87955,
      longitude: 29.8327,
    },
    {
      name: "Hangar De La Bpae)",
      province: "Ngozi",
      commune: "Ngozi",
      zone: "Ngozi Urbain",
      latitude: -2.91503,
      longitude: 29.8202,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Rumonge",
      commune: "Bugarama",
      zone: "Magara",
      latitude: -3.72206,
      longitude: 29.326,
    },
    {
      name: "Salle Communal",
      province: "Rumonge",
      commune: "Bugarama",
      zone: "Bugarama",
      latitude: -3.69256,
      longitude: 29.35723,
    },
    {
      name: "Salle Communal",
      province: "Rumonge",
      commune: "Muhuta",
      zone: "Gitaza",
      latitude: -3.6105,
      longitude: 29.3475,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Rumonge",
      commune: "Rumonge",
      zone: "Kigwena",
      latitude: -4.14995,
      longitude: 29.52767,
    },
    {
      name: "Salle Du -Du Cfp Birimba",
      province: "Rumonge",
      commune: "Rumonge",
      zone: "Rumonge",
      latitude: -3.98427,
      longitude: 29.44739,
    },
    {
      name: "HANGAR PROVINCIAL BUSEBWA ",
      province: "Rumonge",
      commune: "Rumonge",
      zone: "Gatete",
      latitude: -4.06222,
      longitude: 29.50587,
    },
    {
      name: "Salle Communal",
      province: "Rumonge",
      commune: "Buyengero",
      zone: "Muyama",
      latitude: -3.81453,
      longitude: 29.54254,
    },
    {
      name: "Salle Communal",
      province: "Rumonge",
      commune: "Burambi",
      zone: "Murago",
      latitude: -3.79939,
      longitude: 29.44114,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Rumonge",
      commune: "Rumonge",
      zone: "Gatete",
      latitude: -4.04757,
      longitude: 29.4827,
    },
    {
      name: "Salle  Du Bureau Zonal",
      province: "Rumonge",
      commune: "Rumonge",
      zone: "Buruhukiro",
      latitude: -3.98617,
      longitude: 29.54142,
    },
    {
      name: "Colline Muramba",
      province: "Rutana",
      commune: "Rutana",
      zone: "Rutana",
      latitude: -3.92666,
      longitude: 29.99053,
    },
    {
      name: "MAGASIN DE STOCKAGE NYAMUNYONGA",
      province: "Rutana",
      commune: "Rutana",
      zone: "Rutana",
      latitude: -3.9511,
      longitude: 29.99606,
    },
    {
      name: "GRENIER COMMUNAUTAIRE DE GITABA",
      province: "Rutana",
      commune: "Rutana",
      zone: "Gitaba",
      latitude: -3.87276,
      longitude: 29.97019,
    },
    {
      name: "GRENIER COMMUNAUTAIRE DE NGOMA",
      province: "Rutana",
      commune: "Musongati",
      zone: "Ngoma",
      latitude: -3.77336,
      longitude: 30.00835,
    },
    {
      name: "GRENIER COMMUNAUTAIRE COOPERATIVE TURASHOBOYE",
      province: "Rutana",
      commune: "Musongati",
      zone: "Musongati",
      latitude: -3.72653,
      longitude: 30.09898,
    },
    {
      name: "GRENIER COMMUNAUTAIRE MPINGA",
      province: "Rutana",
      commune: "Mpinga-Kayove",
      zone: "Mpinga",
      latitude: -3.73452,
      longitude: 30.17783,
    },
    {
      name: "GRENIER COMMUNAUTAIRE DE  KAYERO",
      province: "Rutana",
      commune: "Mpinga-Kayove",
      zone: "Kayero",
      latitude: -3.79667,
      longitude: 30.15686,
    },
    {
      name: "GRENIER COMMUNAUTAIRE DE KIGUHU",
      province: "Rutana",
      commune: "Mpinga-Kayove",
      zone: "Kiguhu",
      latitude: -3.88798,
      longitude: 30.12105,
    },
    {
      name: "GRENIER COMMUNAUTAIRE DE GAKUNGU",
      province: "Rutana",
      commune: "Giharo",
      zone: "Gakungu",
      latitude: -3.75152,
      longitude: 30.32247,
    },
    {
      name: "HANGAR RUTOKE",
      province: "Rutana",
      commune: "Mpinga-Kayove",
      zone: "Mugondo",
      latitude: -3.65681,
      longitude: 30.21367,
    },
    {
      name: "GRENIER COMMUNAUTAIRE DE MUZYE ",
      province: "Rutana",
      commune: "Giharo",
      zone: "Muzye",
      latitude: -3.98689,
      longitude: 30.1273,
    },
    {
      name: "HANGAR COMMUNAUTAIRE DE RUBANGA",
      province: "Rutana",
      commune: "Giharo",
      zone: "Butezi",
      latitude: -3.82223,
      longitude: 30.21186,
    },
    {
      name: "HANGAR  DE GIHARO",
      province: "Rutana",
      commune: "Giharo",
      zone: "Giharo",
      latitude: -3.78007,
      longitude: 30.23543,
    },
    {
      name: "HANGAR DE STOCKAGE COMMUNAUTAIRE GITANGA",
      province: "Rutana",
      commune: "Gitanga",
      zone: "Gitanga",
      latitude: -3.98482,
      longitude: 29.9561,
    },
    {
      name: "HANGAR KINZANZA ",
      province: "Rutana",
      commune: "Gitanga",
      zone: "Kinzanza",
      latitude: -4.06079,
      longitude: 29.94321,
    },
    {
      name: "Hangar Bukemba",
      province: "Rutana",
      commune: "Bukemba",
      zone: "Bukemba",
      latitude: -4.0068,
      longitude: 30.07025,
    },
    {
      name: "Hangar Butare",
      province: "Rutana",
      commune: "Bukemba",
      zone: "Butare",
      latitude: -3.99597,
      longitude: 29.98785,
    },
    {
      name: "Muhwazi",
      province: "Ruyigi",
      commune: "Nyabitsinda",
      zone: "Muhwazi",
      latitude: -3.63831,
      longitude: 30.24512,
    },
    {
      name: "Hangar Bureau Zonal",
      province: "Ruyigi",
      commune: "Nyabitsinda",
      zone: "Muhwazi",
      latitude: -3.62768,
      longitude: 30.25292,
    },
    {
      name: "CEM VUMWE",
      province: "Ruyigi",
      commune: "Kinyinya",
      zone: "Kinyinya",
      latitude: -3.61309,
      longitude: 30.31212,
    },
    {
      name: "Hangar Caem",
      province: "Ruyigi",
      commune: "Nyabitsinda",
      zone: "Nyabitsinda",
      latitude: -3.54048,
      longitude: 30.27524,
    },
    {
      name: "HANGAR KARINDO",
      province: "Ruyigi",
      commune: "Kinyinya",
      zone: "Kinyinya",
      latitude: -3.6104,
      longitude: 30.34221,
    },
    {
      name: "Kabanga",
      province: "Ruyigi",
      commune: "Kinyinya",
      zone: "Kabanga",
      latitude: -3.58768,
      longitude: 30.38959,
    },
    {
      name: "Kinyinya 1",
      province: "Ruyigi",
      commune: "Kinyinya",
      zone: "Kinyinya",
      latitude: -3.65956,
      longitude: 30.34748,
    },
    {
      name: "Kinyinya 2",
      province: "Ruyigi",
      commune: "Kinyinya",
      zone: "Kinyinya",
      latitude: -3.65916,
      longitude: 30.34206,
    },
    {
      name: "Gisuru 1",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Gisuru",
      latitude: -3.45737,
      longitude: 30.49898,
    },
    {
      name: "Gisuru2",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Gisuru",
      latitude: -3.45771,
      longitude: 30.504,
    },
    {
      name: "HANGAR PARUWASI GISURU",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Gisuru",
      latitude: -3.45004,
      longitude: 30.51019,
    },
    {
      name: "CEM NDEMEKA",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Ndemeka",
      latitude: -3.44323,
      longitude: 30.59251,
    },
    {
      name: "CEM NYABITARE",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Nyabitare",
      latitude: -3.45597,
      longitude: 30.40387,
    },
    {
      name: "Gacokwe",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Ndemeka",
      latitude: -3.43187,
      longitude: 30.5532,
    },
    {
      name: "Ndemeka",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Ndemeka",
      latitude: -3.45,
      longitude: 30.57755,
    },
    {
      name: "Nyabitare",
      province: "Ruyigi",
      commune: "Gisuru",
      zone: "Nyabitare",
      latitude: -3.45166,
      longitude: 30.4086,
    },
    {
      name: "Butezi",
      province: "Ruyigi",
      commune: "Butezi",
      zone: "Butezi",
      latitude: -3.39195,
      longitude: 30.15305,
    },
    {
      name: "CDS BUTEZI",
      province: "Ruyigi",
      commune: "Butezi",
      zone: "Butezi",
      latitude: -3.39062,
      longitude: 30.16494,
    },
    {
      name: "Bwagiriza",
      province: "Ruyigi",
      commune: "Butezi",
      zone: "Bwagiriza",
      latitude: -3.3525,
      longitude: 30.28252,
    },
    {
      name: "Mubira",
      province: "Ruyigi",
      commune: "Butezi",
      zone: "Mubira",
      latitude: -3.40542,
      longitude: 30.08256,
    },
    {
      name: "Busoro",
      province: "Ruyigi",
      commune: "Bweru",
      zone: "Busoro",
      latitude: -3.25306,
      longitude: 30.43217,
    },
    {
      name: "Kayongozi",
      province: "Ruyigi",
      commune: "Bweru",
      zone: "Kayongozi",
      latitude: -3.27331,
      longitude: 30.33494,
    },
    {
      name: "Kirambi",
      province: "Ruyigi",
      commune: "Bweru",
      zone: "Kirambi",
      latitude: -3.32188,
      longitude: 30.46907,
    },
    {
      name: "Mubavu",
      province: "Ruyigi",
      commune: "Bweru",
      zone: "Mubavu",
      latitude: -3.33073,
      longitude: 30.39874,
    },
    {
      name: "Biyorwa",
      province: "Ruyigi",
      commune: "Butaganzwa/Ruyigi",
      zone: "Biyorwa",
      latitude: -3.47706,
      longitude: 30.11261,
    },
    {
      name: "Mugege",
      province: "Ruyigi",
      commune: "Butaganzwa/Ruyigi",
      zone: "Mugege",
      latitude: -3.59052,
      longitude: 30.17904,
    },
    {
      name: "Muriza",
      province: "Ruyigi",
      commune: "Butaganzwa/Ruyigi",
      zone: "Muriza",
      latitude: -3.56238,
      longitude: 30.14623,
    },
    {
      name: "Rugongo",
      province: "Ruyigi",
      commune: "Butaganzwa/Ruyigi",
      zone: "Rugongo",
      latitude: -3.45616,
      longitude: 30.16415,
    },
    {
      name: "MURIZA 2",
      province: "Ruyigi",
      commune: "Butaganzwa/Ruyigi",
      zone: "Muriza",
      latitude: -3.56038,
      longitude: 30.14736,
    },
    {
      name: "Bisinde",
      province: "Ruyigi",
      commune: "Ruyigi",
      zone: "Bisinde",
      latitude: -3.49246,
      longitude: 30.19059,
    },
    {
      name: "Rusengo",
      province: "Ruyigi",
      commune: "Ruyigi",
      zone: "Rusengo",
      latitude: -3.40258,
      longitude: 30.3481,
    },
    {
      name: "Ruyigi",
      province: "Ruyigi",
      commune: "Ruyigi",
      zone: "Ruyigi",
      latitude: -3.47406,
      longitude: 30.25319,
    },
    {
      name: "NYAMUTOBO 1",
      province: "Ruyigi",
      commune: "Ruyigi",
      zone: "Ruyigi",
      latitude: -3.47091,
      longitude: 30.25932,
    },
    {
      name: "STOCK NYAMUTOBO 2 DESENGORGEMENT",
      province: "Ruyigi",
      commune: "Ruyigi",
      zone: "Ruyigi",
      latitude: -3.46648,
      longitude: 30.25872,
    },
    {
      name: "SANZU",
      province: "Ruyigi",
      commune: "Ruyigi",
      zone: "Ruyigi",
      latitude: -3.46855,
      longitude: 30.24648,
    },
    {
      name: "GASANDA",
      province: "Ruyigi",
      commune: "Ruyigi",
      zone: "Ruyigi",
      latitude: -3.47724,
      longitude: 30.24819,
    },
  ];

  const [selectedHangar, setSelectedHangar] = useState(data[0]);

  return (
    <div className=" lg:p-4 relative space-y-4">
      <div className=" space-y-6 lg:absolute top-20 left-16 z-999  ">
        <div className="flex flex-col top-0 left-0 w-full lg:w-max mt-4 shadow-xl lg:mt-0 bg-white dark:bg-gray-900 dark:border-gray-800 text-gray-900 transition-all duration-300 ease-in-out z-50 border rounded-2xl border-gray-200">
          <div className="overflow-y-auto overflow-x-auto lg:overflow-x-hidden flex flex-col justify-between flex-grow">
            <ul className="flex flex-col py-4 space-y-1">
              <div>
                <div className="max-w-full mx-auto rounded-lg overflow-hidden">
                  <div className="px-6 py-4">
                    <h3 className=" text-gray-600 text-sm dark:text-white/90">
                      Information du Hangar
                    </h3>
                    <h3 className="mt-1 font-bold text-gray-900 dark:text-white/90">
                      {selectedHangar?.name || "-"}
                    </h3>
                    <h3 className="mt-1 font-medium text-gray-900 dark:text-white/90">
                      Adresse
                    </h3>
                    <p className="mt-1 text-gray-600 dark:text-white/70 text-sm">
                      {/* Replace with real address if available */}
                      {selectedHangar?.province || "-"} /{" "}
                      {selectedHangar?.commune || "-"} /{" "}
                      {selectedHangar?.zone || "-"}
                    </p>
                    <div className="grid grid-cols-2 gap-4 mt-2">
                      <div>
                        <p className="text-sm font-medium text-gray-800 dark:text-white/90">
                          Longitude
                        </p>
                        <p className="mt-2 text-xs leading-normal text-gray-500 dark:text-gray-400">
                          {selectedHangar?.longitude || "-"}
                        </p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-gray-800 dark:text-white/90">
                          Latitude
                        </p>
                        <p className="mt-2 text-xs leading-normal text-gray-500 dark:text-gray-400">
                          {selectedHangar?.latitude || "-"}
                        </p>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4 mt-2">
                      <div>
                        <p className="text-sm font-medium text-gray-800 dark:text-white/90">
                          Capacite actuelle
                        </p>
                        <p className="mt-2 text-xs leading-normal text-gray-500 dark:text-gray-400">
                          {/* Replace with real data if available */}-
                        </p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-gray-800 dark:text-white/90">
                          Capacite maximale
                        </p>
                        <p className="mt-2 text-xs leading-normal text-gray-500 dark:text-gray-400">
                          {/* Replace with real data if available */}-
                        </p>
                      </div>
                      <div>
                        <Button
                          className="bg-green-600 hover:bg-green-600 disabled:bg-green-600"
                          disabled={selectedHangar.name == null}
                        >
                          Voir detail
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </ul>
          </div>
        </div>
      </div>

      <div className="col-spa/n-4 lg:col-s/pan-3 h-[80vh] space-y-6 overflow-x-auto rounded">
        <MapWithNoSSR
          data={data}
          onMarkerClick={setSelectedHangar}
          onFilterClick={setSelectedHangar}
        />
      </div>
    </div>
  );
}

export default GlobalMap;
